artifacts_root: artifacts #it will create directory

#inside directory we have to ingest the data
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Naveen3251/Dataset/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
